# Generated by Django 4.0.5 on 2022-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='User_Name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Date_of_Birth',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Ornizations',
            field=models.CharField(default=1, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Positions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
