# Generated by Django 4.0.5 on 2022-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usermodel_user_name_usermodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Date_of_Birth',
            field=models.CharField(max_length=20),
        ),
    ]
