# Generated by Django 4.0.5 on 2022-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Date_of_Birth',
            field=models.DateField(max_length=8),
        ),
    ]
