# Generated by Django 4.0.5 on 2022-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
