# Generated by Django 4.0.5 on 2022-06-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Contect',
            field=models.IntegerField(blank='false', max_length=10),
        ),
    ]
