# Generated by Django 4.0.5 on 2022-06-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usermodel_contect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
