# Generated by Django 4.0.5 on 2022-06-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Image',
        ),
    ]
