# Generated by Django 4.0.6 on 2022-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Please_Upload_Image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
